import {
  faHistory,
  faFlagCheckered,
  faUsers,
  faRocket,
  faHeart,
  faBullseye,
  faShieldAlt,
  faTruck,
  faHeadset,
  faLock,
  faCheckCircle,
  faAward,
  faStar,
  faTag,
  faCreditCard,
  faShippingFast,
  faBox,
  faSnowflake,
  faInfoCircle,
  faEnvelope,
  faPhone,
  faClock,
  faMapMarkerAlt,
  faShoppingCart,
  faPaperPlane,
  faChartLine,
  faEdit,
  faTrash,
  faEye,
  faEyeSlash,
  faSearch,
  faUser,
  faHome,
  faImage,
  faTags,
  faLightbulb,
  faGem,
  faFire,
  faCrown,
  faTrophy,
  faMedal,
  faHandshake,
  faGlobe,
  faLeaf,
  faSun,
  faMoon,
  faCloud,
  faBolt,
  faWandMagicSparkles,
  faStarHalfStroke,
  faThumbsUp,
  faThumbsDown,
  faHeartPulse,
  faHandsHelping,
  faUserGroup,
  faUsersGear,
  faUserTie,
  faGraduationCap,
  faBook,
  faBookOpen,
  faScroll,
  faCertificate,
  faRibbon,
  faGift,
  faGifts,
  faCakeCandles,
  faCandyCane,
  faCookie,
  faMugHot,
  faWineGlass,
  faChampagneGlasses,
  faMartiniGlass,
  faBeer,
  faPizzaSlice,
  faBurger,
  faHotdog,
  faIceCream,
  faFish,
  faDrumstickBite,
  faAppleWhole,
  faCarrot,
  faPepperHot,
  faBreadSlice,
  faCheese,
  faEgg,
  faBowlFood,
  faUtensils,
  faSeedling,
  faTree,
  faMountain,
  faWater,
  faUmbrella,
  faCloudRain,
  faCloudSun,
  faCloudMoon,
  faIcicles,
  faWind,
  faDroplet,
  faSprayCan,
} from '@fortawesome/free-solid-svg-icons'
import { faWhatsapp } from '@fortawesome/free-brands-svg-icons'

export const availableIcons = [
  { name: 'faHistory', icon: faHistory, label: 'História' },
  { name: 'faFlagCheckered', icon: faFlagCheckered, label: 'Bandeira' },
  { name: 'faUsers', icon: faUsers, label: 'Usuários' },
  { name: 'faRocket', icon: faRocket, label: 'Foguete' },
  { name: 'faHeart', icon: faHeart, label: 'Coração' },
  { name: 'faBullseye', icon: faBullseye, label: 'Alvo' },
  { name: 'faShieldAlt', icon: faShieldAlt, label: 'Escudo' },
  { name: 'faTruck', icon: faTruck, label: 'Caminhão' },
  { name: 'faHeadset', icon: faHeadset, label: 'Headset' },
  { name: 'faLock', icon: faLock, label: 'Cadeado' },
  { name: 'faCheckCircle', icon: faCheckCircle, label: 'Check' },
  { name: 'faAward', icon: faAward, label: 'Prêmio' },
  { name: 'faStar', icon: faStar, label: 'Estrela' },
  { name: 'faTag', icon: faTag, label: 'Tag' },
  { name: 'faCreditCard', icon: faCreditCard, label: 'Cartão' },
  { name: 'faShippingFast', icon: faShippingFast, label: 'Entrega' },
  { name: 'faBox', icon: faBox, label: 'Caixa' },
  { name: 'faSnowflake', icon: faSnowflake, label: 'Floco de Neve' },
  { name: 'faInfoCircle', icon: faInfoCircle, label: 'Info' },
  { name: 'faEnvelope', icon: faEnvelope, label: 'Envelope' },
  { name: 'faPhone', icon: faPhone, label: 'Telefone' },
  { name: 'faClock', icon: faClock, label: 'Relógio' },
  { name: 'faMapMarkerAlt', icon: faMapMarkerAlt, label: 'Localização' },
  { name: 'faShoppingCart', icon: faShoppingCart, label: 'Carrinho' },
  { name: 'faPaperPlane', icon: faPaperPlane, label: 'Avião de Papel' },
  { name: 'faChartLine', icon: faChartLine, label: 'Gráfico' },
  { name: 'faEdit', icon: faEdit, label: 'Editar' },
  { name: 'faTrash', icon: faTrash, label: 'Lixeira' },
  { name: 'faEye', icon: faEye, label: 'Olho' },
  { name: 'faEyeSlash', icon: faEyeSlash, label: 'Olho Fechado' },
  { name: 'faSearch', icon: faSearch, label: 'Buscar' },
  { name: 'faUser', icon: faUser, label: 'Usuário' },
  { name: 'faHome', icon: faHome, label: 'Casa' },
  { name: 'faImage', icon: faImage, label: 'Imagem' },
  { name: 'faTags', icon: faTags, label: 'Tags' },
  { name: 'faLightbulb', icon: faLightbulb, label: 'Lâmpada' },
  { name: 'faGem', icon: faGem, label: 'Gema' },
  { name: 'faFire', icon: faFire, label: 'Fogo' },
  { name: 'faCrown', icon: faCrown, label: 'Coroa' },
  { name: 'faTrophy', icon: faTrophy, label: 'Troféu' },
  { name: 'faMedal', icon: faMedal, label: 'Medalha' },
  { name: 'faHandshake', icon: faHandshake, label: 'Aperto de Mão' },
  { name: 'faGlobe', icon: faGlobe, label: 'Globo' },
  { name: 'faLeaf', icon: faLeaf, label: 'Folha' },
  { name: 'faSun', icon: faSun, label: 'Sol' },
  { name: 'faMoon', icon: faMoon, label: 'Lua' },
  { name: 'faCloud', icon: faCloud, label: 'Nuvem' },
  { name: 'faBolt', icon: faBolt, label: 'Raio' },
  { name: 'faWandMagicSparkles', icon: faWandMagicSparkles, label: 'Varinha Mágica' },
  { name: 'faStarHalfStroke', icon: faStarHalfStroke, label: 'Meia Estrela' },
  { name: 'faThumbsUp', icon: faThumbsUp, label: 'Curtir' },
  { name: 'faThumbsDown', icon: faThumbsDown, label: 'Descurtir' },
  { name: 'faHeartPulse', icon: faHeartPulse, label: 'Coração Pulsante' },
  { name: 'faHandsHelping', icon: faHandsHelping, label: 'Mãos Ajudando' },
  { name: 'faUserGroup', icon: faUserGroup, label: 'Grupo de Usuários' },
  { name: 'faUsersGear', icon: faUsersGear, label: 'Usuários e Engrenagem' },
  { name: 'faUserTie', icon: faUserTie, label: 'Usuário com Gravata' },
  { name: 'faGraduationCap', icon: faGraduationCap, label: 'Capelo' },
  { name: 'faBook', icon: faBook, label: 'Livro' },
  { name: 'faBookOpen', icon: faBookOpen, label: 'Livro Aberto' },
  { name: 'faScroll', icon: faScroll, label: 'Pergaminho' },
  { name: 'faCertificate', icon: faCertificate, label: 'Certificado' },
  { name: 'faRibbon', icon: faRibbon, label: 'Fita' },
  { name: 'faGift', icon: faGift, label: 'Presente' },
  { name: 'faGifts', icon: faGifts, label: 'Presentes' },
  { name: 'faCakeCandles', icon: faCakeCandles, label: 'Bolo com Velas' },
  { name: 'faCandyCane', icon: faCandyCane, label: 'Bastão de Doce' },
  { name: 'faCookie', icon: faCookie, label: 'Biscoito' },
  { name: 'faMugHot', icon: faMugHot, label: 'Caneca Quente' },
  { name: 'faWineGlass', icon: faWineGlass, label: 'Taça de Vinho' },
  { name: 'faChampagneGlasses', icon: faChampagneGlasses, label: 'Taças de Champanhe' },
  { name: 'faMartiniGlass', icon: faMartiniGlass, label: 'Taça de Martini' },
  { name: 'faBeer', icon: faBeer, label: 'Cerveja' },
  { name: 'faPizzaSlice', icon: faPizzaSlice, label: 'Fatia de Pizza' },
  { name: 'faBurger', icon: faBurger, label: 'Hambúrguer' },
  { name: 'faHotdog', icon: faHotdog, label: 'Cachorro Quente' },
  { name: 'faIceCream', icon: faIceCream, label: 'Sorvete' },
  { name: 'faFish', icon: faFish, label: 'Peixe' },
  { name: 'faDrumstickBite', icon: faDrumstickBite, label: 'Coxa de Frango' },
  { name: 'faAppleWhole', icon: faAppleWhole, label: 'Maçã' },
  { name: 'faCarrot', icon: faCarrot, label: 'Cenoura' },
  { name: 'faPepperHot', icon: faPepperHot, label: 'Pimenta' },
  { name: 'faBreadSlice', icon: faBreadSlice, label: 'Fatia de Pão' },
  { name: 'faCheese', icon: faCheese, label: 'Queijo' },
  { name: 'faEgg', icon: faEgg, label: 'Ovo' },
  { name: 'faBowlFood', icon: faBowlFood, label: 'Tigela de Comida' },
  { name: 'faUtensils', icon: faUtensils, label: 'Talheres' },
  { name: 'faSeedling', icon: faSeedling, label: 'Muda' },
  { name: 'faTree', icon: faTree, label: 'Árvore' },
  { name: 'faMountain', icon: faMountain, label: 'Montanha' },
  { name: 'faWater', icon: faWater, label: 'Água' },
  { name: 'faUmbrella', icon: faUmbrella, label: 'Guarda-chuva' },
  { name: 'faCloudRain', icon: faCloudRain, label: 'Nuvem com Chuva' },
  { name: 'faCloudSun', icon: faCloudSun, label: 'Nuvem com Sol' },
  { name: 'faCloudMoon', icon: faCloudMoon, label: 'Nuvem com Lua' },
  { name: 'faIcicles', icon: faIcicles, label: 'Ciclos de Gelo' },
  { name: 'faWind', icon: faWind, label: 'Vento' },
  { name: 'faDroplet', icon: faDroplet, label: 'Gota' },
  { name: 'faSprayCan', icon: faSprayCan, label: 'Spray' },
  { name: 'faWhatsapp', icon: faWhatsapp, label: 'WhatsApp' },
]

export const getIconByName = (iconName: string) => {
  const icon = availableIcons.find(i => i.name === iconName)
  return icon ? icon.icon : faHistory
}

